version: "3.2"

services:
  memotion_app:
    image: memotion-python-poetry:3.9
    build:
      context: backend/.devcontainer
      dockerfile: Dockerfile
    container_name: memotion_app
    working_dir: /usr/src
    tty: true
    user: memotion_app
    volumes:
      - type: bind
        source: ./backend
        target: /usr/src/backend
      - type: bind
        source: ./.git
        target: /usr/src/.git
      - type: bind
        source: ./.vscode
        target: /usr/src/.vscode

  memotion_web:
    image: memotion-node:14
    build:
      context: frontend/.devcontainer
      dockerfile: Dockerfile
    container_name: memotion_web
    working_dir: /usr/src
    tty: true
    user: memotion_web
    volumes:
      - type: bind
        source: ./frontend
        target: /usr/src/frontend
      - type: bind
        source: ./.git
        target: /usr/src/.git
      - type: bind
        source: ./.vscode
        target: /usr/src/.vscode
