version: "3.2"

services:
  memotion_app:
    image: memotion-python-poetry:3.9
    build:
      context: backend/.devcontainer
      dockerfile: Dockerfile
    container_name: memotion_app
    working_dir: /usr/src
    tty: true
    user: memotion_app
    volumes:
      - $HOME/.ssh:/home/memotion_app/.ssh
      - .:/usr/src:cached
      - ./.vscode/cspell.json:/usr/src/backend/.vscode/cspell.json:cached

  memotion_web:
    image: memotion-node:14
    build:
      context: frontend/.devcontainer
      dockerfile: Dockerfile
    container_name: memotion_web
    working_dir: /usr/src
    tty: true
    user: memotion_web
    volumes:
      - $HOME/.ssh:/home/memotion_web/.ssh
      - .:/usr/src:cached
      - ./.vscode/cspell.json:/usr/src/frontend/.vscode/cspell.json:cached
